package srcvndb

import (
	"time"

	"gorm.io/datatypes"
)

type Char struct {
	ID          string    `gorm:"primaryKey" json:"id"`
	Image       string    `gorm:"not null" json:"image"`
	BloodT      string    `gorm:"column:bloodt;not null" json:"bloodt"`
	CupSize     string    `gorm:"column:cup_size;not null" json:"cup_size"`
	Sex         string    `gorm:"not null" json:"sex"`
	SpoilSex    string    `gorm:"column:spoil_sex;not null" json:"spoil_sex"`
	Gender      string    `gorm:"not null" json:"gender"`
	SpoilGender string    `gorm:"column:spoil_gender;not null" json:"spoil_gender"`
	Main        string    `gorm:"not null" json:"main"`
	MainSpoil   int16     `gorm:"not null" json:"main_spoil"`
	SBust       int16     `gorm:"column:s_bust;not null" json:"s_bust"`
	SWaist      int16     `gorm:"column:s_waist;not null" json:"s_waist"`
	SHip        int16     `gorm:"column:s_hip;not null" json:"s_hip"`
	Birthday    int16     `gorm:"not null" json:"birthday"`
	Height      int16     `gorm:"not null" json:"height"`
	Weight      *int16    `gorm:"column:weight" json:"weight"`
	Age         *int16    `gorm:"column:age" json:"age"`
	Description string    `gorm:"not null" json:"description"`
	IngestedAt  time.Time `gorm:"not null" json:"ingested_at"`
}

func (Char) TableName() string { return "src_vndb.chars" }

type CharName struct {
	ID    string `gorm:"primaryKey;column:id" json:"id"`
	Lang  string `gorm:"primaryKey;column:lang" json:"lang"`
	Name  string `gorm:"not null" json:"name"`
	Latin string `gorm:"not null" json:"latin"`
}

func (CharName) TableName() string { return "src_vndb.chars_names" }

type CharVN struct {
	Seq int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"-"`
	// Explicit column tags: GORM would snake-case VID/RID to v_id/r_id (the
	// acronym column-naming trap) — pin them to the dump's names.
	ID    string `gorm:"column:id;not null;index" json:"id"`
	VID   string `gorm:"column:vid;not null;index" json:"vid"`
	RID   string `gorm:"column:rid;not null" json:"rid"`
	Role  string `gorm:"not null" json:"role"`
	Spoil int16  `gorm:"not null" json:"spoil"`
}

func (CharVN) TableName() string { return "src_vndb.chars_vns" }

type VN struct {
	ID          string    `gorm:"primaryKey" json:"id"`
	OLang       string    `gorm:"column:olang;not null" json:"olang"`
	Image       string    `gorm:"not null" json:"image"`
	CImage      string    `gorm:"column:c_image;not null" json:"c_image"`
	Description string    `gorm:"not null" json:"description"`
	CVotecount  int       `gorm:"column:c_votecount;not null" json:"c_votecount"`
	CRating     *float64  `gorm:"column:c_rating;type:numeric" json:"c_rating"`
	CAverage    *float64  `gorm:"column:c_average;type:numeric" json:"c_average"`
	CLength     *int      `gorm:"column:c_length" json:"c_length"`
	CLengthnum  int       `gorm:"column:c_lengthnum;not null" json:"c_lengthnum"`
	Length      int16     `gorm:"not null" json:"length"`
	Devstatus   int16     `gorm:"not null" json:"devstatus"`
	Alias       string    `gorm:"not null" json:"alias"`
	IngestedAt  time.Time `gorm:"not null" json:"ingested_at"`
}

func (VN) TableName() string { return "src_vndb.vn" }

// VNTitle is the VN-grain title table. It is NOT releases_titles: a release
// title is packaging ("… 初回限定版", "… 18+ Patch") and stamps bundle names on
// every VN a compilation contains, which is why the zh source lane has to
// filter it. vn.olang carries an upstream FK to vn_titles(id, lang), so every
// VN has a row for its own original language.
type VNTitle struct {
	ID       string `gorm:"primaryKey;column:id" json:"id"`
	Lang     string `gorm:"primaryKey;column:lang" json:"lang"`
	Official bool   `gorm:"not null" json:"official"`
	Title    string `gorm:"not null" json:"title"`
	Latin    string `gorm:"not null" json:"latin"`
}

func (VNTitle) TableName() string { return "src_vndb.vn_titles" }

// Staged from the separate votes dump, not from the database dump. That dump
// omits every vote cast by a user whose list is private, so Total is at most
// VN.CVotecount and typically a few percent under it — the two are different
// populations and must never be reconciled into each other.
type VNVoteStats struct {
	ID           string         `gorm:"primaryKey" json:"id"`
	Distribution datatypes.JSON `gorm:"type:jsonb;not null" json:"distribution"`
	Total        int            `gorm:"not null" json:"total"`
}

func (VNVoteStats) TableName() string { return "src_vndb.vn_vote_stats" }

type VNRelation struct {
	ID       string `gorm:"primaryKey;column:id" json:"id"`
	VID      string `gorm:"primaryKey;column:vid" json:"vid"`
	Relation string `gorm:"not null" json:"relation"`
	Official bool   `gorm:"not null" json:"official"`
}

func (VNRelation) TableName() string { return "src_vndb.vn_relations" }

type Image struct {
	ID             string `gorm:"primaryKey" json:"id"`
	Width          int    `gorm:"not null" json:"width"`
	Height         int    `gorm:"not null" json:"height"`
	VoteCount      int    `gorm:"column:c_votecount;not null" json:"c_votecount"`
	SexualAvg      int16  `gorm:"column:c_sexual_avg;not null" json:"c_sexual_avg"`
	SexualStddev   int16  `gorm:"column:c_sexual_stddev;not null" json:"c_sexual_stddev"`
	ViolenceAvg    int16  `gorm:"column:c_violence_avg;not null" json:"c_violence_avg"`
	ViolenceStddev int16  `gorm:"column:c_violence_stddev;not null" json:"c_violence_stddev"`
	Weight         int16  `gorm:"column:c_weight;not null" json:"c_weight"`
}

func (Image) TableName() string { return "src_vndb.images" }

type PortraitBackfill struct {
	CatalogCharacterID int64  `gorm:"primaryKey;autoIncrement:false" json:"catalog_character_id"`
	VNDBCharID         string `gorm:"not null" json:"vndb_char_id"`
	ImageID            string `gorm:"not null" json:"image_id"`
	SexualAvg          int16  `gorm:"not null" json:"sexual_avg"`
	ViolenceAvg        int16  `gorm:"not null" json:"violence_avg"`
}

func (PortraitBackfill) TableName() string { return "src_vndb.portrait_backfill" }

type IngestRun struct {
	ID         int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DumpLabel  string    `gorm:"not null" json:"dump_label"`
	Counts     string    `gorm:"not null;type:jsonb;default:'{}'" json:"counts"`
	DurationMS int64     `gorm:"not null" json:"duration_ms"`
	StartedAt  time.Time `gorm:"not null" json:"started_at"`
}

func (IngestRun) TableName() string { return "src_vndb.ingest_run" }
