package editing

import (
	"context"
	"fmt"
	"sort"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const SuppressedFieldSuffix = ".suppressed"

const (
	maxSuppressedKeys     = 200
	maxSuppressedKeyRunes = 512
)

// SuppressedRow is negative knowledge about one row of a multi-source list
// field: the row stays in its own table because the importer owns it and will
// re-push it, and every read path drops it instead. IdentityKey is derived from
// the row's content by the registering field, never from its database id — an
// importer that deletes and re-inserts the row hands it a new id, which would
// silently expire the suppression.
type SuppressedRow struct {
	ID          int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	EntityType  string    `gorm:"not null;uniqueIndex:uq_edit_suppressed_row,priority:1" json:"entity_type"`
	EntityID    int64     `gorm:"not null;uniqueIndex:uq_edit_suppressed_row,priority:2" json:"entity_id"`
	FieldKey    string    `gorm:"not null;uniqueIndex:uq_edit_suppressed_row,priority:3" json:"field_key"`
	IdentityKey string    `gorm:"type:text;not null;uniqueIndex:uq_edit_suppressed_row,priority:4" json:"identity_key"`
	CreatedAt   time.Time `json:"created_at"`
}

func (SuppressedRow) TableName() string { return "edit_suppressed_row" }

func SuppressedFieldKey(parentKey string) string { return parentKey + SuppressedFieldSuffix }

// SuppressedFieldSpec builds the companion field that carries a list field's
// suppression set. It copies the parent's Policy; the caller must append the
// result to the same field slice its SiteOverlays are built from, or the
// companion silently ends up more permissive than the field it suppresses.
func SuppressedFieldSpec(entityType string, parent FieldSpec) FieldSpec {
	parentKey := parent.Key
	key := SuppressedFieldKey(parentKey)
	limit := parent.MaxSuppressed
	if limit <= 0 {
		limit = maxSuppressedKeys
	}
	var check func(string) error
	if parent.Identity != nil {
		check = parent.Identity.KeyCheck
	}
	parse := func(v any) ([]string, error) {
		keys, err := ParseSuppressedKeys(v, limit)
		if err != nil || check == nil {
			return keys, err
		}
		for i, k := range keys {
			if err := check(k); err != nil {
				return nil, fmt.Errorf("element %d: %w", i, err)
			}
		}
		return keys, nil
	}
	return FieldSpec{
		Key:           key,
		Kind:          KindList,
		DiffHint:      DiffHintItems,
		Policy:        parent.Policy,
		MaxSuppressed: limit,
		MaxElements:   limit,
		Value:         &ValueSpec{Element: &ElementSpec{Type: "text"}},
		Validate: func(v any) error {
			_, err := parse(v)
			return err
		},
		Apply: func(ctx context.Context, tx *gorm.DB, entityID int64, value any) error {
			keys, err := parse(value)
			if err != nil {
				return &ValidationError{Key: key, Reason: err.Error()}
			}
			return ReconcileSuppressed(ctx, tx, entityType, entityID, parentKey, keys)
		},
	}
}

// ParseSuppressedKeys accepts only the canonical shape: ascending, deduplicated
// identity keys. Existence is deliberately not checked — suppressing a row that
// is not in the table yet is the whole point, because the importer re-pushes
// deleted rows after the suppression is recorded.
func ParseSuppressedKeys(v any, maxKeys int) ([]string, error) {
	arr, ok := v.([]any)
	if !ok {
		return nil, fmt.Errorf("must be an array of identity keys")
	}
	if maxKeys <= 0 {
		maxKeys = maxSuppressedKeys
	}
	if len(arr) > maxKeys {
		return nil, fmt.Errorf("must contain at most %d identity keys", maxKeys)
	}
	out := make([]string, 0, len(arr))
	for i, el := range arr {
		s, ok := el.(string)
		if !ok {
			return nil, fmt.Errorf("element %d: must be a string", i)
		}
		if s == "" {
			return nil, fmt.Errorf("element %d: must not be empty", i)
		}
		if len([]rune(s)) > maxSuppressedKeyRunes {
			return nil, fmt.Errorf("element %d: must be at most %d characters", i, maxSuppressedKeyRunes)
		}
		if i > 0 && s <= out[i-1] {
			return nil, fmt.Errorf("element %d: identity keys must be sorted ascending and unique", i)
		}
		out = append(out, s)
	}
	return out, nil
}

func ReconcileSuppressed(ctx context.Context, tx *gorm.DB, entityType string, entityID int64, fieldKey string, keys []string) error {
	del := tx.WithContext(ctx).
		Where("entity_type = ? AND entity_id = ? AND field_key = ?", entityType, entityID, fieldKey)
	if len(keys) > 0 {
		del = del.Where("identity_key NOT IN ?", keys)
	}
	if err := del.Delete(&SuppressedRow{}).Error; err != nil {
		return err
	}
	if len(keys) == 0 {
		return nil
	}
	rows := make([]SuppressedRow, 0, len(keys))
	for _, k := range keys {
		rows = append(rows, SuppressedRow{
			EntityType: entityType, EntityID: entityID, FieldKey: fieldKey, IdentityKey: k,
		})
	}
	return tx.WithContext(ctx).Clauses(clause.OnConflict{DoNothing: true}).Create(&rows).Error
}

func LoadSuppressedKeys(ctx context.Context, db *gorm.DB, entityType string, entityID int64, fieldKey string) ([]string, error) {
	var keys []string
	if err := db.WithContext(ctx).Model(&SuppressedRow{}).
		Where("entity_type = ? AND entity_id = ? AND field_key = ?", entityType, entityID, fieldKey).
		Pluck("identity_key", &keys).Error; err != nil {
		return nil, err
	}
	// Sorted in Go, not in SQL: ParseSuppressedKeys demands byte order and the
	// database's collation is not byte order, so an ORDER BY here would hand
	// back a snapshot the validator rejects.
	sort.Strings(keys)
	return keys, nil
}

// LoadSuppressedValue returns the snapshot value for a `.suppressed` field. The
// slice is never nil: a nil and an empty list encode differently in the
// revision snapshot and would make every no-op edit look like a change.
func LoadSuppressedValue(ctx context.Context, db *gorm.DB, entityType string, entityID int64, fieldKey string) ([]any, error) {
	keys, err := LoadSuppressedKeys(ctx, db, entityType, entityID, fieldKey)
	if err != nil {
		return nil, err
	}
	out := make([]any, 0, len(keys))
	for _, k := range keys {
		out = append(out, k)
	}
	return out, nil
}

func SuppressedKeysFor(ctx context.Context, db *gorm.DB, entityType, fieldKey string, entityIDs []int64) (map[int64]map[string]struct{}, error) {
	if len(entityIDs) == 0 {
		return map[int64]map[string]struct{}{}, nil
	}
	return collectSuppressed(ctx, db, entityType, fieldKey, entityIDs)
}

func AllSuppressedKeys(ctx context.Context, db *gorm.DB, entityType, fieldKey string) (map[int64]map[string]struct{}, error) {
	return collectSuppressed(ctx, db, entityType, fieldKey, nil)
}

func collectSuppressed(ctx context.Context, db *gorm.DB, entityType, fieldKey string, entityIDs []int64) (map[int64]map[string]struct{}, error) {
	q := db.WithContext(ctx).Model(&SuppressedRow{}).
		Select("entity_id", "identity_key").
		Where("entity_type = ? AND field_key = ?", entityType, fieldKey)
	if entityIDs != nil {
		q = q.Where("entity_id IN ?", entityIDs)
	}
	var rows []SuppressedRow
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	out := make(map[int64]map[string]struct{}, len(rows))
	for _, r := range rows {
		set, ok := out[r.EntityID]
		if !ok {
			set = make(map[string]struct{}, 4)
			out[r.EntityID] = set
		}
		set[r.IdentityKey] = struct{}{}
	}
	return out, nil
}
