package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	v2handler "api/internal/platform/apiv2/handler"
	"api/internal/platform/apiv2/problem"
	"api/internal/platform/apiv2/vocab"
	"api/internal/platform/mcpface"

	"github.com/gofiber/fiber/v3"
)

func main() {
	out := flag.String("o", "", "output directory")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "-o is required")
		os.Exit(1)
	}
	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := writeProblems(*out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := writeVocab(*out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := writeMCPTools(*out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func writeProblems(dir string) error {
	type row struct {
		Code        string `json:"code"`
		Domain      string `json:"domain"`
		Kebab       string `json:"kebab"`
		Status      int    `json:"status"`
		Title       string `json:"title"`
		Description string `json:"description"`
		Type        string `json:"type"`
	}
	rows := make([]row, 0, len(problem.Codes))
	for _, d := range problem.Codes {
		rows = append(rows, row{
			Code: d.Code, Domain: string(d.Domain), Kebab: problem.Kebab(d.Code),
			Status: d.Status, Title: d.Title, Description: d.Description, Type: d.TypeURI(),
		})
	}
	return writeTS(filepath.Join(dir, "problems.ts"), "problems", rows)
}

func writeVocab(dir string) error {
	type val struct {
		Value       string `json:"value"`
		DisplayName string `json:"display_name"`
		Description string `json:"description"`
	}
	type voc struct {
		Name   string `json:"name"`
		Closed bool   `json:"closed"`
		Values []val  `json:"values"`
	}
	all := vocab.All()
	rows := make([]voc, 0, len(all))
	for _, v := range all {
		item := voc{Name: v.Name, Closed: v.Closed}
		for _, x := range v.Values {
			item.Values = append(item.Values, val{Value: x.Value, DisplayName: x.DisplayName, Description: x.Description})
		}
		rows = append(rows, item)
	}
	return writeTS(filepath.Join(dir, "vocabularies.ts"), "vocabularies", rows)
}

// The portal's MCP page and its Markdown twin list the tools the MCP server
// actually registers. That list is mcpface.ToolsFromSpec applied to the v2
// document — the same call registerSpecTools makes at boot — so it is derived
// here instead of hand-kept: the previous hand-written roster spent a release
// naming v1-era tools that no longer existed.
func writeMCPTools(dir string) error {
	raw, err := json.Marshal(v2handler.Setup(fiber.New()).OpenAPI())
	if err != nil {
		return err
	}
	tools, err := mcpface.ToolsFromSpec(raw)
	if err != nil {
		return err
	}
	type row struct {
		Name     string   `json:"name"`
		Method   string   `json:"method"`
		Path     string   `json:"path"`
		Summary  string   `json:"summary"`
		NeedsKey bool     `json:"needs_key"`
		Params   []string `json:"params"`
	}
	rows := make([]row, 0, len(tools))
	for _, t := range tools {
		params := t.Params
		if params == nil {
			params = []string{}
		}
		rows = append(rows, row{
			Name: t.Name, Method: t.Method, Path: t.Path,
			Summary: t.Summary, NeedsKey: t.NeedsKey, Params: params,
		})
	}
	return writeMJS(filepath.Join(dir, "mcp-tools.mjs"), "mcpTools", rows)
}

// .mjs, not .ts, because scripts/gen-llms.mjs consumes this under bare node with
// no TypeScript loader — the same reason shared/mcp-tools.mjs is not a .ts file.
func writeMJS(path, export string, v any) error {
	raw, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen-v2-portal. DO NOT EDIT.\n\n")
	buf.WriteString("export const " + export + " = ")
	buf.Write(raw)
	buf.WriteString("\n")
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func writeTS(path, export string, v any) error {
	raw, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen-v2-portal. DO NOT EDIT.\n\n")
	buf.WriteString("export const " + export + " = ")
	buf.Write(raw)
	buf.WriteString(" as const\n")
	return os.WriteFile(path, buf.Bytes(), 0o644)
}
