package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"api/internal/platform/apiv2/problem"
	"api/internal/platform/apiv2/vocab"
)

func main() {
	out := flag.String("o", "", "output directory")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "-o is required")
		os.Exit(1)
	}
	if err := os.MkdirAll(*out, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := writeProblems(*out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := writeVocab(*out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func writeProblems(dir string) error {
	type row struct {
		Code        string `json:"code"`
		Domain      string `json:"domain"`
		Kebab       string `json:"kebab"`
		Status      int    `json:"status"`
		Title       string `json:"title"`
		Description string `json:"description"`
		Type        string `json:"type"`
	}
	rows := make([]row, 0, len(problem.Codes))
	for _, d := range problem.Codes {
		rows = append(rows, row{
			Code: d.Code, Domain: string(d.Domain), Kebab: problem.Kebab(d.Code),
			Status: d.Status, Title: d.Title, Description: d.Description, Type: d.TypeURI(),
		})
	}
	return writeTS(filepath.Join(dir, "problems.ts"), "problems", rows)
}

func writeVocab(dir string) error {
	type val struct {
		Value       string `json:"value"`
		DisplayName string `json:"display_name"`
		Description string `json:"description"`
	}
	type voc struct {
		Name   string `json:"name"`
		Closed bool   `json:"closed"`
		Values []val  `json:"values"`
	}
	all := vocab.All()
	rows := make([]voc, 0, len(all))
	for _, v := range all {
		item := voc{Name: v.Name, Closed: v.Closed}
		for _, x := range v.Values {
			item.Values = append(item.Values, val{Value: x.Value, DisplayName: x.DisplayName, Description: x.Description})
		}
		rows = append(rows, item)
	}
	return writeTS(filepath.Join(dir, "vocabularies.ts"), "vocabularies", rows)
}

func writeTS(path, export string, v any) error {
	raw, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen-v2-portal. DO NOT EDIT.\n\n")
	buf.WriteString("export const " + export + " = ")
	buf.Write(raw)
	buf.WriteString(" as const\n")
	return os.WriteFile(path, buf.Bytes(), 0o644)
}
