package model

import "time"

const (
	KindPurchase = "purchase"
	KindCoupon   = "coupon"
)

type PurchaseLink struct {
	ID        int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ClientID  string `gorm:"size:50;not null;uniqueIndex:uq_store_purchase_link,priority:1" json:"client_id"`
	ProductID string `gorm:"size:32;not null;uniqueIndex:uq_store_purchase_link,priority:2" json:"product_id"`
	// Alias is unique so that a regression in the shortener's reuse:false
	// handling fails loudly instead of quietly. Every site's link for one
	// product targets the same affiliate URL, so a shortener that resumed
	// reusing by destination would hand two clients the same alias — and
	// without this constraint both rows would store it and the two sites'
	// clicks would merge into one bucket with nothing to show for it.
	// Attribution is the only thing this domain exists to measure, so the
	// second mint must 5xx and page an operator rather than silently
	// mis-settle. Same reasoning on store_coupon_links.alias.
	Alias     string    `gorm:"size:64;not null;uniqueIndex:uq_store_purchase_alias" json:"alias"`
	ShortURL  string    `gorm:"type:text;not null" json:"short_url"`
	CreatedAt time.Time `json:"created_at"`
}

func (PurchaseLink) TableName() string { return "store_purchase_links" }

type CouponLink struct {
	ID         int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ClientID   string    `gorm:"size:50;not null;uniqueIndex:uq_store_coupon_link,priority:1" json:"client_id"`
	CampaignID int64     `gorm:"not null;uniqueIndex:uq_store_coupon_link,priority:2" json:"campaign_id"`
	Alias      string    `gorm:"size:64;not null;uniqueIndex:uq_store_coupon_alias" json:"alias"`
	ShortURL   string    `gorm:"type:text;not null" json:"short_url"`
	CreatedAt  time.Time `json:"created_at"`
}

func (CouponLink) TableName() string { return "store_coupon_links" }

type Campaign struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Name      string    `gorm:"size:100;not null" json:"name"`
	CouponURL string    `gorm:"type:text;not null" json:"coupon_url"`
	StartsAt  time.Time `gorm:"not null;index" json:"starts_at"`
	EndsAt    time.Time `gorm:"not null;index" json:"ends_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (Campaign) TableName() string { return "store_campaigns" }

type LinkDailyStat struct {
	ID    int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Alias string `gorm:"size:64;not null;uniqueIndex:uq_store_link_daily,priority:1" json:"alias"`
	// A JST calendar-day LABEL as the shortener contract spells it
	// ("YYYY-MM-DD"), never a timestamp: the settlement month is DLsite's JST
	// calendar month, and a `date` column would invite a session-timezone
	// conversion on every read and write. developer_api_usage.day in this same
	// database is varchar(10) for the same reason.
	Day      string    `gorm:"size:10;not null;uniqueIndex:uq_store_link_daily,priority:2" json:"day"`
	Total    int64     `gorm:"not null" json:"total"`
	Uniques  int64     `gorm:"not null" json:"uniques"`
	SyncedAt time.Time `gorm:"not null" json:"synced_at"`
}

func (LinkDailyStat) TableName() string { return "store_link_daily_stats" }

func AllModels() []any {
	return []any{&PurchaseLink{}, &CouponLink{}, &Campaign{}, &LinkDailyStat{}}
}
