package model

import (
	"time"

	"gorm.io/datatypes"
)

type PriceQuote struct {
	ID              int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Source          string `gorm:"size:32;not null;uniqueIndex:uq_store_price_quote,priority:1"`
	ExternalID      string `gorm:"size:64;not null;uniqueIndex:uq_store_price_quote,priority:2"`
	Region          string `gorm:"size:8;not null;uniqueIndex:uq_store_price_quote,priority:3"`
	QuoteState      string `gorm:"size:16;not null"`
	URL             string `gorm:"type:text;not null"`
	Currency        string `gorm:"size:3;not null;default:''"`
	ListMinor       int64  `gorm:"not null;default:0"`
	CurrentMinor    int64  `gorm:"not null;default:0"`
	DiscountPercent int16  `gorm:"not null;default:0"`
	SaleEndsAt      *time.Time
	// minor units (amount × 100)
	Converted       datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'"`
	FetchedAt       time.Time      `gorm:"not null"`
	ExpiresAt       time.Time      `gorm:"not null;index"`
	LastRequestedAt time.Time      `gorm:"not null;index"`
	CreatedAt       time.Time
}

func (PriceQuote) TableName() string { return "store_price_quotes" }
